/*
 File:          recursion.h
 Purpose:       Prototypes for lab 4 exercises
 Author:			  Your names
 Student #s:		12345678 and 12345678
 CS Accounts:		a1a1 and b2b2
 Date:				  Add the date here
 */

#pragma once

/******************************************************************
 PLEASE DO NOT EDIT THIS FILE
 ******************************************************************/

int calculate_power(int base, int power);
int count_digits(int number);
int string_length( char* string );
int is_palindrome(char* string, int string_length);
int draw_ramp( int number, char* buffer );
int draw_row( int size, char* buffer );