/*
File:         discrete_fourier_transform.h
Purpose:      Contains prototypes for a fast discrete Fourier
transformation based on code available at:
http://paulbourke.net/miscellaneous/dft/
Author:			  Your names
Student #s:		12345678 and 12345678
CS Accounts:	a1a1 and b2b2
Date:				  Add the date here
*/

/********************************************************************
DO NOT EDIT THIS FILE
******************************************************************/

#pragma once

/* Function prototype */
void fft(short int dir, long m, double x[], double y[]);